import requests

headers = {
    'authority': 'repl.it',
    'accept': '*/*',
    'x-requested-with': 'XMLHttpRequest',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51',
    'content-type': 'application/json',
    'origin': 'https://repl.it',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://repl.it/',
    'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8',
    'cookie': '_ga=GA1.2.787519420.1600026205; connect.sid=s%3AV9CcvdR3T-TWwvamwJik41EK3xxkqLNc.cFNAG5SKt5d%2Beetzzk6px4NRx2Wm5dIrVl%2B8XMxxgik; ajs_anonymous_id=%22ada2d781-6f7f-4f11-b861-62730da53c98%22; _gid=GA1.2.2011677991.1600361287; _gat=1; __cfduid=d00e279cf04a9344665a188f0e0678f581600361287',
}

data = '{\"operationName\":\"NewReplCreateRepl\",\"variables\":{\"input\":{\"title\":\"\",\"isPrivate\":false,\"language\":\"python3\"},\"isTitleAutoGenerated\":false},\"query\":\"mutation NewReplCreateRepl($input: CreateReplInput!, $isTitleAutoGenerated: Boolean!) {\\n  createRepl(input: $input, isTitleAutoGenerated: $isTitleAutoGenerated) {\\n    ...NewReplOutput\\n    __typename\\n  }\\n}\\n\\nfragment NewReplOutput on CreateReplOutput {\\n  ... on Repl {\\n    id\\n    url\\n    __typename\\n  }\\n  ... on UserError {\\n    message\\n    __typename\\n  }\\n  __typename\\n}\\n\"}'

while True:
    response = requests.post('https://repl.it/graphql', headers=headers, data=data)
    print(response.json())
